name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  addInnerHTMLJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run custom action
        id: custom-action
        run: npm run build

      - name: Display innerHTML output
        id: display-output
        run: echo "innerHTML: ${{ steps.custom-action.outputs.innerHTML }}"
